blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.thanks,name='thanks'),
    path('projects/', views.ProjectView.as_view(), name='projects'),
    path('projects/<slug:slug>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='detail')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=400)
    text = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class About(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    image = models.FileField(blank=True)
    github = models.URLField()
    linkedin = models.URLField()
    instagram = models.URLField()
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=400)
    text = models.TextField()
    repo_link = models.URLField() 
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.mail import send_mail
from django.urls import reverse
from blogsite.email_settings import *

from .tracking import *
from .CONSTANTS import *
from snowplow_tracker import SelfDescribingJson

class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    t = create_tracker()

    def send_email(self):
        sender_name = self.cleaned_data['name']
        sender_email = self.cleaned_data['email']

        message = "{0} has sent you a new message:\n\n{1}\n\nContact Email: {2}".format(sender_name, self.cleaned_data['message'], self.cleaned_data['email'])
        send_mail('New Enquiry', message, sender_email, [EMAIL_HOST_USER], fail_silently=False)

        self.t.track_form_submit("contact_me")
        

        

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from django.urls import reverse

from .models import Post, About, Project
from .forms import ContactForm
from .tracking import *
from .CONSTANTS import *



class HomeView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    t = create_tracker()

    def get_queryset(self):
        url = BLOG_URL + reverse('blog:index')
        self.t.track_page_view(url, "home")

        return Post.objects.filter(
            created_on__lte=timezone.now()
        ).order_by('-created_on')



class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

    t = create_tracker()

    def get_queryset(self):
        posts = Post.objects.filter(created_on__lte=timezone.now())
        post = posts[0]

        url = BLOG_URL + reverse('blog:index') + post.slug
        self.t.track_page_view(url, post.slug)
        
        return posts



class ProjectView(generic.ListView):
    template_name = 'blog/projects.html'
    context_object_name = 'projects_list'

    t = create_tracker()

    def get_queryset(self):
        url = BLOG_URL + reverse('blog:projects')
        self.t.track_page_view(url, "projects")

        return Project.objects.filter(
            created_on__lte=timezone.now()
        ).order_by('-created_on')



class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'blog/project-detail.html'

    t = create_tracker()

    def get_queryset(self):
        projects = Project.objects.filter(created_on__lte=timezone.now())
        project = projects[0]

        url = BLOG_URL + reverse('blog:projects') + project.slug
        self.t.track_page_view(url, "Project -" + project.slug)
        
        return projects



class AboutView(generic.ListView):
    template_name = 'blog/about.html'
    context_object_name = 'about'

    t = create_tracker()

    def get_queryset(self):
        url = BLOG_URL + reverse('blog:about')
        self.t.track_page_view(url, "About")

        return About.objects.first()



class ContactView(generic.edit.FormView):
    template_name = 'blog/contact.html'
    form_class = ContactForm
    success_url = '/home/thanks'

    t = create_tracker()

    def get_initial(self):
        url = BLOG_URL + reverse('blog:contact')
        self.t.track_page_view(url, "Contact")
        return super().get_initial()

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)



def thanks(request):
    t = create_tracker()
    url = BLOG_URL + reverse('blog:thanks')
    t.track_page_view(url, "Thanks")

    return(render(request,template_name='blog/thanks.html'))

blog/templates/blog/about.html
{% include "blog/navbar.html" %}
<div class="about">
    {% if about %}
        <div class="about-info">        
            <h1 class="name">{{ about.name }}</h1>
            <p>{{ about.text }}</p>
            <p><a href={{ about.github }}>{{ about.github }}</a></p>
            <p><a href={{ about.linkedin }}>{{ about.linkedin }}</a></p>
            <p><a href={{ about.instagram }}>{{ about.instagram }}</a></p>
            <p class="updated">{{ about.updated_on }}</p>
        </div>
    {% else %}
        <div class="not-available">
            <p>No information available</p>
        </div>
    {% endif %}
</div>

blog/templates/blog/contact.html
{% include "blog/navbar.html" %}

<div class="content">
    <div class="Form">
        <h1>Contact Me</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send Message" />
        </form>
    </div>
</div>

blog/templates/blog/detail.html
{% include "blog/navbar.html" %}

<div class="blog-detail">
    <h1>{{ post.title }}</h1>
    <p>{{ post.text }}</p>
    <p class="updated">Last Updated: {{ post.updated_on }}</p>
</div>

blog/templates/blog/index.html
{% include "blog/navbar.html" %}
<div class="content">
    {% if post_list %}
        <h1>Blog Posts:</h1>
        <dl class="blog-list">
        {% for post in post_list %}
            <div class="post-details">
                <a href="{% url 'blog:detail' post.slug %}">
                    <dt>{{ post.title }}</dt>
                    <p>{{ post.description }}</p>
                    <dd>{{ post.created_on }}</dd>
                </a>
            </div>
        {% endfor %}
        </dl>
    {% else %}
        <div class="not-available">
            <p>No posts available</p>
        </div>
    {% endif %}
</div>

blog/templates/blog/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet"> 

<div class="navbar">
    <a class="logo" href={% url 'blog:index' %}>
        <img src="{% static 'blog/logo.png' %}">
    </a>
    <ul>
        <li class="nav-link"><a href={% url 'blog:contact' %}>Contact</a></li>
        <li class="nav-link"><a href={% url 'blog:about' %}>About</a></li>
        <li class="nav-link"><a href={% url 'blog:projects' %}>Projects</a></li>
        <li class="nav-link"><a href={% url 'blog:index' %}>Blog</a></li>
    </ul>
</div>

blog/templates/blog/project-detail.html
{% include "blog/navbar.html" %}

<div class="blog-detail">
    <h1>{{ project.title }}</h1>
    <p>{{ project.text }}</p>
    <p class="updated">Last Updated: {{ project.updated_on }}</p>
</div>

blog/templates/blog/projects.html
{% include "blog/navbar.html" %}
<div class="content">
    {% if projects_list %}
        <h1>Projects:</h1>
        <dl class="blog-list">
        {% for project in projects_list %}
            <div class="post-details">
                <a href="{% url 'blog:project-detail' project.slug %}">
                    <dt>{{ project.title }}</dt>
                    <p>{{ project.description }}</p>
                    <dd>{{ project.created_on }}</dd>
                </a>
            </div>
        {% endfor %}
        </dl>
    {% else %}
        <div class="not-available">
            <p>No projects available</p>
        </div>
    {% endif %}
</div>

blog/templates/blog/thanks.html
{% include "blog/navbar.html" %}

<div class="content">
    <div class="thanks">
        <a href={% url 'blog:index' %}>
            <h1>Thank you for your message!</h1>
            <p>I'll be in touch for any queries shortly</p>
            <p>Click to return home</p>
        </a>
    </div>
</div>